### ISSUE TITLE
Выдача опыта при смерти от мира (DeathRun)

### ISSUE THREAD

**Issue by kleuser75** [levelsranks/levels-ranks-core#34]
Вообщем имеется дезран сервер, на нем когда человек умирает от мира(ловушек) не выдается очки террористу, опция для передачи фрагов для террориста соответственно включена в моде. Shop засчитывает, а ЛР не хочет.

Раньше в старых версиях всё выдавалось нормально. Сейчас бывает выдается опыт только на первой карте после запуска сервера(и то не всегда), дальше перестает выдавать как карта меняется.

Скажу сразу я уверен, что это не от плагина дезрана т.к перепробовал все плагины, и на всех одно и тоже. Это с какой-то версии ЛР стало так, а вот с какой фиг его знает.

**Comment by senator1** [comment]
+++

**Comment by Wend4r** [comment]
решается путём переписки плагина deathrun на SDKHook_OnTakeDamage, если игрок получил урон от мира.

**Comment by kleuser75** [comment]
> решается путём переписки плагина deathrun на SDKHook_OnTakeDamage, если игрок получил урон от мира (ловушек) с указанием iAttacker(а) - террориста.

А причем тут плагин дезрана, если проблема в LR ? После выхода 3.0 рангов, он перестал зачитывать смерти от мира. Почему нельзя вернуть это в LR ?

**Comment by Wend4r** [comment]
Потому что ранний хук событий был сделан для того, чтобы другие плагины создающий своё Event событие не могли конфликтовать с LR.
