### ISSUE TITLE
Spam in log

### ISSUE THREAD

**Issue by BetweenJuck** [levelsranks/levels-ranks-core#38]
Taken from addons/sourcemod/logs/errors_20200722.log
L 07/22/2020 - 23:09:42: [SM] Exception reported: Invalid index -1 (count: 18)
L 07/22/2020 - 23:09:42: [SM] Blaming: levelsranks.smx
L 07/22/2020 - 23:09:42: [SM] Call stack trace:
L 07/22/2020 - 23:09:42: [SM]   [0] ArrayList.GetString
L 07/22/2020 - 23:09:42: [SM]   [1] Line 291, levels_ranks/custom_functions.sp::CheckRank
L 07/22/2020 - 23:09:42: [SM]   [2] Line 233, levels_ranks/custom_functions.sp::NotifClient
L 07/22/2020 - 23:09:42: [SM]   [3] Line 103, levels_ranks/events.sp::Event_PlayerDeath
L 07/22/2020 - 23:10:18: [SM] Exception reported: Invalid index -1 (count: 18)
L 07/22/2020 - 23:10:18: [SM] Blaming: levelsranks.smx
L 07/22/2020 - 23:10:18: [SM] Call stack trace:
L 07/22/2020 - 23:10:18: [SM]   [0] ArrayList.GetString
L 07/22/2020 - 23:10:18: [SM]   [1] Line 291, levels_ranks/custom_functions.sp::CheckRank
L 07/22/2020 - 23:10:18: [SM]   [2] Line 233, levels_ranks/custom_functions.sp::NotifClient
L 07/22/2020 - 23:10:18: [SM]   [3] Line 234, levels_ranks/events.sp::Events_Rounds
L 07/22/2020 - 23:10:45: [SM] Exception reported: Invalid index -1 (count: 18)
L 07/22/2020 - 23:10:45: [SM] Blaming: levelsranks.smx
L 07/22/2020 - 23:10:45: [SM] Call stack trace:
L 07/22/2020 - 23:10:45: [SM]   [0] ArrayList.GetString
L 07/22/2020 - 23:10:45: [SM]   [1] Line 291, levels_ranks/custom_functions.sp::CheckRank
L 07/22/2020 - 23:10:45: [SM]   [2] Line 233, levels_ranks/custom_functions.sp::NotifClient
L 07/22/2020 - 23:10:45: [SM]   [3] Line 103, levels_ranks/events.sp::Event_PlayerDeath
L 07/22/2020 - 23:12:20: [SM] Exception reported: Invalid index -1 (count: 18)
L 07/22/2020 - 23:12:20: [SM] Blaming: levelsranks.smx
L 07/22/2020 - 23:12:20: [SM] Call stack trace:
L 07/22/2020 - 23:12:20: [SM]   [0] ArrayList.GetString
L 07/22/2020 - 23:12:20: [SM]   [1] Line 291, levels_ranks/custom_functions.sp::CheckRank
L 07/22/2020 - 23:12:20: [SM]   [2] Line 233, levels_ranks/custom_functions.sp::NotifClient
L 07/22/2020 - 23:12:20: [SM]   [3] Line 103, levels_ranks/events.sp::Event_PlayerDeath
L 07/22/2020 - 23:22:32: [SM] Exception reported: Invalid index -1 (count: 18)
L 07/22/2020 - 23:22:32: [SM] Blaming: levelsranks.smx
L 07/22/2020 - 23:22:32: [SM] Call stack trace:
L 07/22/2020 - 23:22:32: [SM]   [0] ArrayList.GetString
L 07/22/2020 - 23:22:32: [SM]   [1] Line 291, levels_ranks/custom_functions.sp::CheckRank
L 07/22/2020 - 23:22:32: [SM]   [2] Line 233, levels_ranks/custom_functions.sp::NotifClient
L 07/22/2020 - 23:22:32: [SM]   [3] Line 234, levels_ranks/events.sp::Events_Rounds

**Comment by Wend4r** [comment]
A player cannot have a 0 rank without third party intervention in the database table.
I believe this is not LR Core problem.
