### ISSUE TITLE
The menu does not appear on some players.

### ISSUE THREAD

**Issue by IZOcC** [levelsranks/levels-ranks-core#48]
Does not show the level menu to some people. Type the !lvl command and no menu appears.
Can it be from the server or from the player?
What can create this problem?

Thank you in advance!

**Comment by Wend4r** [comment]
Hello the menu may not open due to an error from the plugin

**Comment by IZOcC** [comment]
The menu runs perfectly for everyone but I have a player that doesn't show up when I type !lvl or /lvl.
Also loaded in the console with sm_lvl.
He tried to install the game again and the problem persists.
I can't explain what it can be from.

**Comment by Wend4r** [comment]
Check for errors in the plugin. If they are when this player enters !lvl (sm_lvl)?

**Comment by IZOcC** [comment]
The problem was solved by itself. I don't know how but it works now.

**Comment by IZOcC** [comment]
Thanks for your time

**Comment by Erik-97** [comment]
because some players has special characters in their names
just use "lr_db_character_type" "1" and there will be no problems

**Comment by IZOcC** [comment]
Thanks for the answers and time.
