### ISSUE TITLE
High SV and FPS drop

### ISSUE THREAD

**Issue by isakjensen** [levelsranks/levels-ranks-core#6]
**I typed this on the official thread on the forum, but I've been told that it's better to post it here. So here's my problem and conclusion/testing:**

I've been testing for hours and hours. Here is my conclusion and when it appears:

- I have 10 Competitive servers. All 10 Competitives have the latest version of the plugin and when all servers are online and they are all full (which they are 80% of the day), the sv value starts increasing. When all servers is full, the sv is up to over 60, which cause all players getting huge fps lag spikes.

- The two first days I had the plugin, the sv went up to around 5-10 only when the round was over. But after a few days, the sv was going up to 30-40 all time which is too much, it shouldn't go over 4 or 5.

- I disabled the rank plugins on all servers, and when the servers became full, the sv was stable at 3 on all servers.

- It has to do with the rank plugin, and when I only have 6 servers online and 4 offline, the sv is only going up to 6. For people that have one or two servers, then this is not a problem for them. But for people that have more than 5, then it becomes a big problem.

Fixing this would be really awesome, I hope i helped with my testing and explanation. Hope you fix it, ask me if you have any questions, I can test on my servers!

**Comment by thanked** [comment]
Are you gonna fix this or what?

**Comment by Wend4r** [comment]
how does it relate to the [Levels Ranks] Core? Perhaps you have a weak database.

**Comment by CrazyHackGUT** [comment]
Can you run profiler? Profiler can help detect problem plugin.

**Comment by thanked** [comment]
> Can you run profiler? Profiler can help detect problem plugin.

What is profiler?

**Comment by CrazyHackGUT** [comment]
`sm prof`
After start, Source Engine and SourceMod will collect statistics for executing any functions with time for executing.

**Comment by thanked** [comment]
So I run 

> sm_rcon sm prof

In the console?

**Comment by CrazyHackGUT** [comment]
No.
`sm_rcon sm prof start`
https://forums.alliedmods.net/showthread.php?t=248581

**Comment by thanked** [comment]
So I run that, where is the result. Does it come in a file?

Or where can I see what the collected statistics is?

**Comment by CrazyHackGUT** [comment]
All information is described on link.

**Comment by thanked** [comment]
Okay, ty. Will try when I’m home

**Comment by ItsCEED** [comment]
I can confirm that you have WEAK database, or LOW power servers.

I had the exact same issue, and i move to VPS just for the database.

**Comment by CrazyHackGUT** [comment]
SQLite or MySQL?

On MySQL, this not should happen. All queries executed in separated thread, called as `SM SQL worker`.

**Comment by Nerus87** [comment]
I had a problem with locking DB by this plugin (transaction), the database was locked and plugin tries to execute transaction couple times but always fail, all plugins frozed, I guess with sourcemod.

> L 03/20/2020 - 18:53:09: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:53:13: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 18:54:19: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:54:20: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 18:55:20: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:55:20: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 18:56:22: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:56:22: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 18:57:23: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:57:24: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 18:58:25: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:58:25: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 18:59:26: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 18:59:26: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 19:00:27: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 19:00:28: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 19:01:29: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 19:01:29: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 19:02:30: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 19:02:31: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 19:03:34: SourceMod error session started
L 03/20/2020 - 19:03:34: [CRASH] Accelerator uploaded crash dump: Crash ID: CJQY-ZJUA-QIQ5
L 03/20/2020 - 19:05:45: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 19:05:45: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 19:06:46: [levelsranks.smx] Reconnect to the Database!
L 03/20/2020 - 19:06:47: [levelsranks.smx] Successfully! Attempt #0.
L 03/20/2020 - 19:07:20: [levelsranks.smx] SQL_Callback Error (338): Duplicate entry 'STEAM_0:0:XXXXXXXXX' for key 'PRIMARY'
L 03/20/2020 - 19:07:20: [levelsranks.smx] SQL_Callback Error (338): Duplicate entry 'STEAM_0:0:XXXXXXXXX' for key 'PRIMARY'

**Comment by Nerus87** [comment]
This can be closed, I don't have any other problem with DB and FPS drops on servers CSGO and CSS.
