### ISSUE TITLE
переход с 3.1.2 на 3.1.6

### ISSUE THREAD

**Issue by mrkvka** [levelsranks/levels-ranks-core#61]
Прошу помочь с переходом со старой на более новую версию с 3.1.2 на 3.1.6. структура базы изменилось но плагин сам не вносит изменения 
пожалуйста, помогите с решением

**Comment by Wend4r** [comment]
С чем вам помочь? Какие проблемы у вас возникают со структурой?

**Comment by mrkvka** [comment]
обновил плагин теперь спамит кучу ошибок. после смены карты опыт сбрасывает на тот что был, не сохраняет ничего. 
Первая ошибка основного плагина SQL_transectionFailure (1): Unkown column 'classname' in 'where clause' (1)
вторая ошибка модуля exstats weapons: loaddataplayer - unkown column 'kills' in 'faield list'

**Comment by Wend4r** [comment]
Это касается модуля ExStats Weapons

**Comment by mrkvka** [comment]
SQL_transectionFailure (1): Unkown column 'classname' in 'where clause' (1) рисует само ядро

**Comment by Wend4r** [comment]
Да, потому что оно является переносчиком транзакций модулей при событии сохранения игрока. Запрос с ошибкой формирует же, в свою очередь, модуль ExStats Weapons

**Comment by mrkvka** [comment]
это проблема самого модуля или просто таблицы моей? мне ждать обновлений или есть какое-нибудь горячее решение чтобы вправить таблицу?

**Comment by Wend4r** [comment]
> это проблема самого модуля или просто таблицы моей?

Проблема структуры таблицы модуля ExStats Weapons.

> мне ждать обновлений

У меня такой задачи не стояло. Зависит только от вас. О способах обновления, я пожалуй промолчу, но их достаточно много.

> или есть какое-нибудь горячее решение чтобы вправить таблицу?

Удалить её, чтобы модуль создал нужную для себя структуру.

**Comment by mrkvka** [comment]
ору. обновил плагин - удаляй всю стату. не хочешь сбрасывать стату - сиди со старой версией. поддержка плагина 100 из 100.

**Comment by Wend4r** [comment]
> обновил плагин - удаляй всю стату. не хочешь сбрасывать стату - сиди со старой версией

Не обязательно, это бесплатный продукт с открытым исходным кодом. Вы можете изменить логику работы плагинов на ваше усмотрение.

> поддержка плагина 100 из 100.

Спасибо за вашу хорошую оценку.
